### ISSUE TITLE
TypeError: Cannot read property 'absolutePath' of null

### ISSUE THREAD

**Issue by StefanMasz** [AOEpeople/raml-validate#1]
`/usr/local/lib/node_modules/aoe-raml-validate/node_modules/raml-1-parser/dist/raml1/ast.core/namespaceResolver.js:177
        var fromPath = unit.absolutePath();
                           ^

TypeError: Cannot read property 'absolutePath' of null
    at NamespaceResolver.nsMap (/usr/local/lib/node_modules/aoe-raml-validate/node_modules/raml-1-parser/dist/raml1/ast.core/namespaceResolver.js:177:28)
    at ReferencePatcher.resolveReferenceValueBasic (/usr/local/lib/node_modules/aoe-raml-validate/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:363:38)
    at ReferencePatcher.resolveReferenceValue (/usr/local/lib/node_modules/aoe-raml-validate/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:329:29)
    at ReferencePatcher.patchType (/usr/local/lib/node_modules/aoe-raml-validate/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:264:44)
    at ReferencePatcher.patchReferences (/usr/local/lib/node_modules/aoe-raml-validate/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:81:18)
    at ReferencePatcher.patchReferences (/usr/local/lib/node_modules/aoe-raml-validate/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.process (/usr/local/lib/node_modules/aoe-raml-validate/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:35:14)
    at TraitsAndResourceTypesExpander.expandHighLevelNode (/usr/local/lib/node_modules/aoe-raml-validate/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:113:16)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (/usr/local/lib/node_modules/aoe-raml-validate/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:91:27)
    at Object.expandTraitsAndResourceTypes (/usr/local/lib/node_modules/aoe-raml-validate/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:27:10)
`

**Comment by StefanMasz** [comment]
Includes from within the RAML are missing. 

-> no Bug, User mistake
